/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PurchaseRequisitionId = IDL.Text;
export const PurchaseRequisitionStatus = IDL.Variant({
  'pendingApproval' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
  'draft' : IDL.Null,
});
export const ApprovalAction = IDL.Variant({
  'submitted' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const ApprovalRecord = IDL.Record({
  'action' : ApprovalAction,
  'approverName' : IDL.Text,
  'timestamp' : IDL.Int,
  'comments' : IDL.Text,
});
export const PurchaseRequisitionItem = IDL.Record({
  'description' : IDL.Text,
  'quantity' : IDL.Nat,
  'estimatedCost' : IDL.Float64,
});
export const PurchaseRequisition = IDL.Record({
  'id' : PurchaseRequisitionId,
  'totalEstimatedCost' : IDL.Float64,
  'status' : PurchaseRequisitionStatus,
  'justification' : IDL.Text,
  'approvalHistory' : IDL.Vec(ApprovalRecord),
  'createdAt' : IDL.Int,
  'updatedAt' : IDL.Int,
  'items' : IDL.Vec(PurchaseRequisitionItem),
  'department' : IDL.Text,
  'requestedBy' : IDL.Text,
});
export const Time = IDL.Int;
export const QuotationRequestId = IDL.Text;
export const RequestStatus = IDL.Variant({
  'closed' : IDL.Null,
  'pending' : IDL.Null,
  'received' : IDL.Null,
});
export const QuotationRequest = IDL.Record({
  'id' : QuotationRequestId,
  'status' : RequestStatus,
  'description' : IDL.Text,
  'quantity' : IDL.Nat,
  'unitOfMeasurement' : IDL.Text,
  'requiredDeliveryDate' : Time,
  'requestDate' : Time,
});
export const VendorId = IDL.Text;
export const VendorStatus = IDL.Variant({
  'active' : IDL.Null,
  'inactive' : IDL.Null,
});
export const Vendor = IDL.Record({
  'id' : VendorId,
  'status' : VendorStatus,
  'contactPerson' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'companyName' : IDL.Text,
  'category' : IDL.Text,
  'phoneNumber' : IDL.Text,
});
export const QuotationId = IDL.Text;
export const QuotationStatus = IDL.Variant({
  'submitted' : IDL.Null,
  'rejected' : IDL.Null,
  'shortlisted' : IDL.Null,
  'accepted' : IDL.Null,
});
export const Quotation = IDL.Record({
  'id' : QuotationId,
  'status' : QuotationStatus,
  'requestId' : QuotationRequestId,
  'validityPeriod' : Time,
  'termsAndConditions' : IDL.Text,
  'vendorId' : VendorId,
  'submissionDate' : Time,
  'deliveryTimeline' : IDL.Text,
  'unitPrice' : IDL.Float64,
  'totalPrice' : IDL.Float64,
});

export const idlService = IDL.Service({
  'approvePurchaseRequisition' : IDL.Func(
      [PurchaseRequisitionId, IDL.Text, IDL.Text],
      [PurchaseRequisition],
      [],
    ),
  'createPurchaseRequisition' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Vec(PurchaseRequisitionItem),
        IDL.Float64,
        IDL.Text,
      ],
      [PurchaseRequisition],
      [],
    ),
  'createQuotationRequest' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, Time],
      [QuotationRequest],
      [],
    ),
  'createVendor' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Vendor],
      [],
    ),
  'deletePurchaseRequisition' : IDL.Func([PurchaseRequisitionId], [], []),
  'deleteVendor' : IDL.Func([VendorId], [], []),
  'getAllQuotationRequests' : IDL.Func(
      [],
      [IDL.Vec(QuotationRequest)],
      ['query'],
    ),
  'getAllVendors' : IDL.Func([], [IDL.Vec(Vendor)], ['query']),
  'getPendingPurchaseRequisitions' : IDL.Func(
      [],
      [IDL.Vec(PurchaseRequisition)],
      ['query'],
    ),
  'getPurchaseRequisitionById' : IDL.Func(
      [PurchaseRequisitionId],
      [IDL.Opt(PurchaseRequisition)],
      ['query'],
    ),
  'getPurchaseRequisitionsWithFilter' : IDL.Func(
      [IDL.Opt(PurchaseRequisitionStatus)],
      [IDL.Vec(PurchaseRequisition)],
      ['query'],
    ),
  'getQuotationRequestsByStatus' : IDL.Func(
      [RequestStatus],
      [IDL.Vec(QuotationRequest)],
      ['query'],
    ),
  'getQuotationsForRequest' : IDL.Func(
      [QuotationRequestId],
      [IDL.Vec(Quotation)],
      ['query'],
    ),
  'getVendor' : IDL.Func([VendorId], [IDL.Opt(Vendor)], ['query']),
  'rejectPurchaseRequisition' : IDL.Func(
      [PurchaseRequisitionId, IDL.Text, IDL.Text],
      [PurchaseRequisition],
      [],
    ),
  'submitForApproval' : IDL.Func(
      [PurchaseRequisitionId],
      [PurchaseRequisition],
      [],
    ),
  'submitQuotation' : IDL.Func(
      [
        VendorId,
        QuotationRequestId,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
        IDL.Text,
        Time,
      ],
      [Quotation],
      [],
    ),
  'updatePurchaseRequisition' : IDL.Func(
      [
        PurchaseRequisitionId,
        IDL.Vec(PurchaseRequisitionItem),
        IDL.Float64,
        IDL.Text,
      ],
      [PurchaseRequisition],
      [],
    ),
  'updateQuotationRequestStatus' : IDL.Func(
      [QuotationRequestId, RequestStatus],
      [QuotationRequest],
      [],
    ),
  'updateQuotationStatus' : IDL.Func(
      [QuotationId, QuotationStatus],
      [Quotation],
      [],
    ),
  'updateVendor' : IDL.Func(
      [
        VendorId,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        VendorStatus,
      ],
      [Vendor],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PurchaseRequisitionId = IDL.Text;
  const PurchaseRequisitionStatus = IDL.Variant({
    'pendingApproval' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
    'draft' : IDL.Null,
  });
  const ApprovalAction = IDL.Variant({
    'submitted' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const ApprovalRecord = IDL.Record({
    'action' : ApprovalAction,
    'approverName' : IDL.Text,
    'timestamp' : IDL.Int,
    'comments' : IDL.Text,
  });
  const PurchaseRequisitionItem = IDL.Record({
    'description' : IDL.Text,
    'quantity' : IDL.Nat,
    'estimatedCost' : IDL.Float64,
  });
  const PurchaseRequisition = IDL.Record({
    'id' : PurchaseRequisitionId,
    'totalEstimatedCost' : IDL.Float64,
    'status' : PurchaseRequisitionStatus,
    'justification' : IDL.Text,
    'approvalHistory' : IDL.Vec(ApprovalRecord),
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Int,
    'items' : IDL.Vec(PurchaseRequisitionItem),
    'department' : IDL.Text,
    'requestedBy' : IDL.Text,
  });
  const Time = IDL.Int;
  const QuotationRequestId = IDL.Text;
  const RequestStatus = IDL.Variant({
    'closed' : IDL.Null,
    'pending' : IDL.Null,
    'received' : IDL.Null,
  });
  const QuotationRequest = IDL.Record({
    'id' : QuotationRequestId,
    'status' : RequestStatus,
    'description' : IDL.Text,
    'quantity' : IDL.Nat,
    'unitOfMeasurement' : IDL.Text,
    'requiredDeliveryDate' : Time,
    'requestDate' : Time,
  });
  const VendorId = IDL.Text;
  const VendorStatus = IDL.Variant({
    'active' : IDL.Null,
    'inactive' : IDL.Null,
  });
  const Vendor = IDL.Record({
    'id' : VendorId,
    'status' : VendorStatus,
    'contactPerson' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'companyName' : IDL.Text,
    'category' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  const QuotationId = IDL.Text;
  const QuotationStatus = IDL.Variant({
    'submitted' : IDL.Null,
    'rejected' : IDL.Null,
    'shortlisted' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const Quotation = IDL.Record({
    'id' : QuotationId,
    'status' : QuotationStatus,
    'requestId' : QuotationRequestId,
    'validityPeriod' : Time,
    'termsAndConditions' : IDL.Text,
    'vendorId' : VendorId,
    'submissionDate' : Time,
    'deliveryTimeline' : IDL.Text,
    'unitPrice' : IDL.Float64,
    'totalPrice' : IDL.Float64,
  });
  
  return IDL.Service({
    'approvePurchaseRequisition' : IDL.Func(
        [PurchaseRequisitionId, IDL.Text, IDL.Text],
        [PurchaseRequisition],
        [],
      ),
    'createPurchaseRequisition' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Vec(PurchaseRequisitionItem),
          IDL.Float64,
          IDL.Text,
        ],
        [PurchaseRequisition],
        [],
      ),
    'createQuotationRequest' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, Time],
        [QuotationRequest],
        [],
      ),
    'createVendor' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Vendor],
        [],
      ),
    'deletePurchaseRequisition' : IDL.Func([PurchaseRequisitionId], [], []),
    'deleteVendor' : IDL.Func([VendorId], [], []),
    'getAllQuotationRequests' : IDL.Func(
        [],
        [IDL.Vec(QuotationRequest)],
        ['query'],
      ),
    'getAllVendors' : IDL.Func([], [IDL.Vec(Vendor)], ['query']),
    'getPendingPurchaseRequisitions' : IDL.Func(
        [],
        [IDL.Vec(PurchaseRequisition)],
        ['query'],
      ),
    'getPurchaseRequisitionById' : IDL.Func(
        [PurchaseRequisitionId],
        [IDL.Opt(PurchaseRequisition)],
        ['query'],
      ),
    'getPurchaseRequisitionsWithFilter' : IDL.Func(
        [IDL.Opt(PurchaseRequisitionStatus)],
        [IDL.Vec(PurchaseRequisition)],
        ['query'],
      ),
    'getQuotationRequestsByStatus' : IDL.Func(
        [RequestStatus],
        [IDL.Vec(QuotationRequest)],
        ['query'],
      ),
    'getQuotationsForRequest' : IDL.Func(
        [QuotationRequestId],
        [IDL.Vec(Quotation)],
        ['query'],
      ),
    'getVendor' : IDL.Func([VendorId], [IDL.Opt(Vendor)], ['query']),
    'rejectPurchaseRequisition' : IDL.Func(
        [PurchaseRequisitionId, IDL.Text, IDL.Text],
        [PurchaseRequisition],
        [],
      ),
    'submitForApproval' : IDL.Func(
        [PurchaseRequisitionId],
        [PurchaseRequisition],
        [],
      ),
    'submitQuotation' : IDL.Func(
        [
          VendorId,
          QuotationRequestId,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
          IDL.Text,
          Time,
        ],
        [Quotation],
        [],
      ),
    'updatePurchaseRequisition' : IDL.Func(
        [
          PurchaseRequisitionId,
          IDL.Vec(PurchaseRequisitionItem),
          IDL.Float64,
          IDL.Text,
        ],
        [PurchaseRequisition],
        [],
      ),
    'updateQuotationRequestStatus' : IDL.Func(
        [QuotationRequestId, RequestStatus],
        [QuotationRequest],
        [],
      ),
    'updateQuotationStatus' : IDL.Func(
        [QuotationId, QuotationStatus],
        [Quotation],
        [],
      ),
    'updateVendor' : IDL.Func(
        [
          VendorId,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          VendorStatus,
        ],
        [Vendor],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };