/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalAction = { 'submitted' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface ApprovalRecord {
  'action' : ApprovalAction,
  'approverName' : string,
  'timestamp' : bigint,
  'comments' : string,
}
export interface PurchaseRequisition {
  'id' : PurchaseRequisitionId,
  'totalEstimatedCost' : number,
  'status' : PurchaseRequisitionStatus,
  'justification' : string,
  'approvalHistory' : Array<ApprovalRecord>,
  'createdAt' : bigint,
  'updatedAt' : bigint,
  'items' : Array<PurchaseRequisitionItem>,
  'department' : string,
  'requestedBy' : string,
}
export type PurchaseRequisitionId = string;
export interface PurchaseRequisitionItem {
  'description' : string,
  'quantity' : bigint,
  'estimatedCost' : number,
}
export type PurchaseRequisitionStatus = { 'pendingApproval' : null } |
  { 'approved' : null } |
  { 'rejected' : null } |
  { 'draft' : null };
export interface Quotation {
  'id' : QuotationId,
  'status' : QuotationStatus,
  'requestId' : QuotationRequestId,
  'validityPeriod' : Time,
  'termsAndConditions' : string,
  'vendorId' : VendorId,
  'submissionDate' : Time,
  'deliveryTimeline' : string,
  'unitPrice' : number,
  'totalPrice' : number,
}
export type QuotationId = string;
export interface QuotationRequest {
  'id' : QuotationRequestId,
  'status' : RequestStatus,
  'description' : string,
  'quantity' : bigint,
  'unitOfMeasurement' : string,
  'requiredDeliveryDate' : Time,
  'requestDate' : Time,
}
export type QuotationRequestId = string;
export type QuotationStatus = { 'submitted' : null } |
  { 'rejected' : null } |
  { 'shortlisted' : null } |
  { 'accepted' : null };
export type RequestStatus = { 'closed' : null } |
  { 'pending' : null } |
  { 'received' : null };
export type Time = bigint;
export interface Vendor {
  'id' : VendorId,
  'status' : VendorStatus,
  'contactPerson' : string,
  'email' : string,
  'address' : string,
  'companyName' : string,
  'category' : string,
  'phoneNumber' : string,
}
export type VendorId = string;
export type VendorStatus = { 'active' : null } |
  { 'inactive' : null };
export interface _SERVICE {
  'approvePurchaseRequisition' : ActorMethod<
    [PurchaseRequisitionId, string, string],
    PurchaseRequisition
  >,
  'createPurchaseRequisition' : ActorMethod<
    [string, string, Array<PurchaseRequisitionItem>, number, string],
    PurchaseRequisition
  >,
  'createQuotationRequest' : ActorMethod<
    [string, bigint, string, Time],
    QuotationRequest
  >,
  'createVendor' : ActorMethod<
    [string, string, string, string, string, string],
    Vendor
  >,
  'deletePurchaseRequisition' : ActorMethod<[PurchaseRequisitionId], undefined>,
  'deleteVendor' : ActorMethod<[VendorId], undefined>,
  'getAllQuotationRequests' : ActorMethod<[], Array<QuotationRequest>>,
  'getAllVendors' : ActorMethod<[], Array<Vendor>>,
  'getPendingPurchaseRequisitions' : ActorMethod<
    [],
    Array<PurchaseRequisition>
  >,
  'getPurchaseRequisitionById' : ActorMethod<
    [PurchaseRequisitionId],
    [] | [PurchaseRequisition]
  >,
  'getPurchaseRequisitionsWithFilter' : ActorMethod<
    [[] | [PurchaseRequisitionStatus]],
    Array<PurchaseRequisition>
  >,
  'getQuotationRequestsByStatus' : ActorMethod<
    [RequestStatus],
    Array<QuotationRequest>
  >,
  'getQuotationsForRequest' : ActorMethod<
    [QuotationRequestId],
    Array<Quotation>
  >,
  'getVendor' : ActorMethod<[VendorId], [] | [Vendor]>,
  'rejectPurchaseRequisition' : ActorMethod<
    [PurchaseRequisitionId, string, string],
    PurchaseRequisition
  >,
  'submitForApproval' : ActorMethod<
    [PurchaseRequisitionId],
    PurchaseRequisition
  >,
  'submitQuotation' : ActorMethod<
    [VendorId, QuotationRequestId, number, number, string, string, Time],
    Quotation
  >,
  'updatePurchaseRequisition' : ActorMethod<
    [PurchaseRequisitionId, Array<PurchaseRequisitionItem>, number, string],
    PurchaseRequisition
  >,
  'updateQuotationRequestStatus' : ActorMethod<
    [QuotationRequestId, RequestStatus],
    QuotationRequest
  >,
  'updateQuotationStatus' : ActorMethod<
    [QuotationId, QuotationStatus],
    Quotation
  >,
  'updateVendor' : ActorMethod<
    [VendorId, string, string, string, string, string, string, VendorStatus],
    Vendor
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];