/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export type QuotationRequestId = string;
export interface PurchaseRequisition {
    id: PurchaseRequisitionId;
    totalEstimatedCost: number;
    status: PurchaseRequisitionStatus;
    justification: string;
    approvalHistory: Array<ApprovalRecord>;
    createdAt: bigint;
    updatedAt: bigint;
    items: Array<PurchaseRequisitionItem>;
    department: string;
    requestedBy: string;
}
export interface ApprovalRecord {
    action: ApprovalAction;
    approverName: string;
    timestamp: bigint;
    comments: string;
}
export interface QuotationRequest {
    id: QuotationRequestId;
    status: RequestStatus;
    description: string;
    quantity: bigint;
    unitOfMeasurement: string;
    requiredDeliveryDate: Time;
    requestDate: Time;
}
export interface Quotation {
    id: QuotationId;
    status: QuotationStatus;
    requestId: QuotationRequestId;
    validityPeriod: Time;
    termsAndConditions: string;
    vendorId: VendorId;
    submissionDate: Time;
    deliveryTimeline: string;
    unitPrice: number;
    totalPrice: number;
}
export type QuotationId = string;
export interface PurchaseRequisitionItem {
    description: string;
    quantity: bigint;
    estimatedCost: number;
}
export type PurchaseRequisitionId = string;
export interface Vendor {
    id: VendorId;
    status: VendorStatus;
    contactPerson: string;
    email: string;
    address: string;
    companyName: string;
    category: string;
    phoneNumber: string;
}
export type VendorId = string;
export enum ApprovalAction {
    submitted = "submitted",
    approved = "approved",
    rejected = "rejected"
}
export enum PurchaseRequisitionStatus {
    pendingApproval = "pendingApproval",
    approved = "approved",
    rejected = "rejected",
    draft = "draft"
}
export enum QuotationStatus {
    submitted = "submitted",
    rejected = "rejected",
    shortlisted = "shortlisted",
    accepted = "accepted"
}
export enum RequestStatus {
    closed = "closed",
    pending = "pending",
    received = "received"
}
export enum VendorStatus {
    active = "active",
    inactive = "inactive"
}
export interface backendInterface {
    approvePurchaseRequisition(requisitionId: PurchaseRequisitionId, approverName: string, comments: string): Promise<PurchaseRequisition>;
    createPurchaseRequisition(requestedBy: string, department: string, items: Array<PurchaseRequisitionItem>, totalEstimatedCost: number, justification: string): Promise<PurchaseRequisition>;
    createQuotationRequest(description: string, quantity: bigint, unitOfMeasurement: string, requiredDeliveryDate: Time): Promise<QuotationRequest>;
    createVendor(companyName: string, contactPerson: string, email: string, phoneNumber: string, address: string, category: string): Promise<Vendor>;
    deletePurchaseRequisition(requisitionId: PurchaseRequisitionId): Promise<void>;
    deleteVendor(vendorId: VendorId): Promise<void>;
    getAllQuotationRequests(): Promise<Array<QuotationRequest>>;
    getAllVendors(): Promise<Array<Vendor>>;
    getPendingPurchaseRequisitions(): Promise<Array<PurchaseRequisition>>;
    getPurchaseRequisitionById(requisitionId: PurchaseRequisitionId): Promise<PurchaseRequisition | null>;
    getPurchaseRequisitionsWithFilter(status: PurchaseRequisitionStatus | null): Promise<Array<PurchaseRequisition>>;
    getQuotationRequestsByStatus(status: RequestStatus): Promise<Array<QuotationRequest>>;
    getQuotationsForRequest(requestId: QuotationRequestId): Promise<Array<Quotation>>;
    getVendor(vendorId: VendorId): Promise<Vendor | null>;
    rejectPurchaseRequisition(requisitionId: PurchaseRequisitionId, approverName: string, comments: string): Promise<PurchaseRequisition>;
    submitForApproval(requisitionId: PurchaseRequisitionId): Promise<PurchaseRequisition>;
    submitQuotation(vendorId: VendorId, requestId: QuotationRequestId, unitPrice: number, totalPrice: number, deliveryTimeline: string, termsAndConditions: string, validityPeriod: Time): Promise<Quotation>;
    updatePurchaseRequisition(requisitionId: PurchaseRequisitionId, items: Array<PurchaseRequisitionItem>, totalEstimatedCost: number, justification: string): Promise<PurchaseRequisition>;
    updateQuotationRequestStatus(requestId: QuotationRequestId, status: RequestStatus): Promise<QuotationRequest>;
    updateQuotationStatus(quotationId: QuotationId, status: QuotationStatus): Promise<Quotation>;
    updateVendor(vendorId: VendorId, companyName: string, contactPerson: string, email: string, phoneNumber: string, address: string, category: string, status: VendorStatus): Promise<Vendor>;
}
import type { ApprovalAction as _ApprovalAction, ApprovalRecord as _ApprovalRecord, PurchaseRequisition as _PurchaseRequisition, PurchaseRequisitionId as _PurchaseRequisitionId, PurchaseRequisitionItem as _PurchaseRequisitionItem, PurchaseRequisitionStatus as _PurchaseRequisitionStatus, Quotation as _Quotation, QuotationId as _QuotationId, QuotationRequest as _QuotationRequest, QuotationRequestId as _QuotationRequestId, QuotationStatus as _QuotationStatus, RequestStatus as _RequestStatus, Time as _Time, Vendor as _Vendor, VendorId as _VendorId, VendorStatus as _VendorStatus } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async approvePurchaseRequisition(arg0: PurchaseRequisitionId, arg1: string, arg2: string): Promise<PurchaseRequisition> {
        if (this.processError) {
            try {
                const result = await this.actor.approvePurchaseRequisition(arg0, arg1, arg2);
                return from_candid_PurchaseRequisition_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approvePurchaseRequisition(arg0, arg1, arg2);
            return from_candid_PurchaseRequisition_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async createPurchaseRequisition(arg0: string, arg1: string, arg2: Array<PurchaseRequisitionItem>, arg3: number, arg4: string): Promise<PurchaseRequisition> {
        if (this.processError) {
            try {
                const result = await this.actor.createPurchaseRequisition(arg0, arg1, arg2, arg3, arg4);
                return from_candid_PurchaseRequisition_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPurchaseRequisition(arg0, arg1, arg2, arg3, arg4);
            return from_candid_PurchaseRequisition_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async createQuotationRequest(arg0: string, arg1: bigint, arg2: string, arg3: Time): Promise<QuotationRequest> {
        if (this.processError) {
            try {
                const result = await this.actor.createQuotationRequest(arg0, arg1, arg2, arg3);
                return from_candid_QuotationRequest_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createQuotationRequest(arg0, arg1, arg2, arg3);
            return from_candid_QuotationRequest_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async createVendor(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<Vendor> {
        if (this.processError) {
            try {
                const result = await this.actor.createVendor(arg0, arg1, arg2, arg3, arg4, arg5);
                return from_candid_Vendor_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createVendor(arg0, arg1, arg2, arg3, arg4, arg5);
            return from_candid_Vendor_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async deletePurchaseRequisition(arg0: PurchaseRequisitionId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePurchaseRequisition(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePurchaseRequisition(arg0);
            return result;
        }
    }
    async deleteVendor(arg0: VendorId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVendor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVendor(arg0);
            return result;
        }
    }
    async getAllQuotationRequests(): Promise<Array<QuotationRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllQuotationRequests();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllQuotationRequests();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllVendors(): Promise<Array<Vendor>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllVendors();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllVendors();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingPurchaseRequisitions(): Promise<Array<PurchaseRequisition>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingPurchaseRequisitions();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingPurchaseRequisitions();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPurchaseRequisitionById(arg0: PurchaseRequisitionId): Promise<PurchaseRequisition | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPurchaseRequisitionById(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPurchaseRequisitionById(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPurchaseRequisitionsWithFilter(arg0: PurchaseRequisitionStatus | null): Promise<Array<PurchaseRequisition>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPurchaseRequisitionsWithFilter(to_candid_opt_n22(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPurchaseRequisitionsWithFilter(to_candid_opt_n22(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuotationRequestsByStatus(arg0: RequestStatus): Promise<Array<QuotationRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuotationRequestsByStatus(to_candid_RequestStatus_n25(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuotationRequestsByStatus(to_candid_RequestStatus_n25(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuotationsForRequest(arg0: QuotationRequestId): Promise<Array<Quotation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuotationsForRequest(arg0);
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuotationsForRequest(arg0);
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVendor(arg0: VendorId): Promise<Vendor | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVendor(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVendor(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async rejectPurchaseRequisition(arg0: PurchaseRequisitionId, arg1: string, arg2: string): Promise<PurchaseRequisition> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectPurchaseRequisition(arg0, arg1, arg2);
                return from_candid_PurchaseRequisition_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectPurchaseRequisition(arg0, arg1, arg2);
            return from_candid_PurchaseRequisition_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitForApproval(arg0: PurchaseRequisitionId): Promise<PurchaseRequisition> {
        if (this.processError) {
            try {
                const result = await this.actor.submitForApproval(arg0);
                return from_candid_PurchaseRequisition_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitForApproval(arg0);
            return from_candid_PurchaseRequisition_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitQuotation(arg0: VendorId, arg1: QuotationRequestId, arg2: number, arg3: number, arg4: string, arg5: string, arg6: Time): Promise<Quotation> {
        if (this.processError) {
            try {
                const result = await this.actor.submitQuotation(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return from_candid_Quotation_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitQuotation(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return from_candid_Quotation_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async updatePurchaseRequisition(arg0: PurchaseRequisitionId, arg1: Array<PurchaseRequisitionItem>, arg2: number, arg3: string): Promise<PurchaseRequisition> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePurchaseRequisition(arg0, arg1, arg2, arg3);
                return from_candid_PurchaseRequisition_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePurchaseRequisition(arg0, arg1, arg2, arg3);
            return from_candid_PurchaseRequisition_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateQuotationRequestStatus(arg0: QuotationRequestId, arg1: RequestStatus): Promise<QuotationRequest> {
        if (this.processError) {
            try {
                const result = await this.actor.updateQuotationRequestStatus(arg0, to_candid_RequestStatus_n25(this._uploadFile, this._downloadFile, arg1));
                return from_candid_QuotationRequest_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateQuotationRequestStatus(arg0, to_candid_RequestStatus_n25(this._uploadFile, this._downloadFile, arg1));
            return from_candid_QuotationRequest_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateQuotationStatus(arg0: QuotationId, arg1: QuotationStatus): Promise<Quotation> {
        if (this.processError) {
            try {
                const result = await this.actor.updateQuotationStatus(arg0, to_candid_QuotationStatus_n33(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Quotation_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateQuotationStatus(arg0, to_candid_QuotationStatus_n33(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Quotation_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateVendor(arg0: VendorId, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: VendorStatus): Promise<Vendor> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVendor(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_VendorStatus_n35(this._uploadFile, this._downloadFile, arg7));
                return from_candid_Vendor_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVendor(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_VendorStatus_n35(this._uploadFile, this._downloadFile, arg7));
            return from_candid_Vendor_n14(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ApprovalAction_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalAction): ApprovalAction {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_ApprovalRecord_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalRecord): ApprovalRecord {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_PurchaseRequisitionStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PurchaseRequisitionStatus): PurchaseRequisitionStatus {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_PurchaseRequisition_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PurchaseRequisition): PurchaseRequisition {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_QuotationRequest_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuotationRequest): QuotationRequest {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_QuotationStatus_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuotationStatus): QuotationStatus {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_Quotation_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Quotation): Quotation {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_RequestStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RequestStatus): RequestStatus {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_VendorStatus_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VendorStatus): VendorStatus {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Vendor_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Vendor): Vendor {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PurchaseRequisition]): PurchaseRequisition | null {
    return value.length === 0 ? null : from_candid_PurchaseRequisition_n1(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Vendor]): Vendor | null {
    return value.length === 0 ? null : from_candid_Vendor_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _QuotationRequestId;
    status: _RequestStatus;
    description: string;
    quantity: bigint;
    unitOfMeasurement: string;
    requiredDeliveryDate: _Time;
    requestDate: _Time;
}): {
    id: QuotationRequestId;
    status: RequestStatus;
    description: string;
    quantity: bigint;
    unitOfMeasurement: string;
    requiredDeliveryDate: Time;
    requestDate: Time;
} {
    return {
        id: value.id,
        status: from_candid_RequestStatus_n12(_uploadFile, _downloadFile, value.status),
        description: value.description,
        quantity: value.quantity,
        unitOfMeasurement: value.unitOfMeasurement,
        requiredDeliveryDate: value.requiredDeliveryDate,
        requestDate: value.requestDate
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _VendorId;
    status: _VendorStatus;
    contactPerson: string;
    email: string;
    address: string;
    companyName: string;
    category: string;
    phoneNumber: string;
}): {
    id: VendorId;
    status: VendorStatus;
    contactPerson: string;
    email: string;
    address: string;
    companyName: string;
    category: string;
    phoneNumber: string;
} {
    return {
        id: value.id,
        status: from_candid_VendorStatus_n16(_uploadFile, _downloadFile, value.status),
        contactPerson: value.contactPerson,
        email: value.email,
        address: value.address,
        companyName: value.companyName,
        category: value.category,
        phoneNumber: value.phoneNumber
    };
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PurchaseRequisitionId;
    totalEstimatedCost: number;
    status: _PurchaseRequisitionStatus;
    justification: string;
    approvalHistory: Array<_ApprovalRecord>;
    createdAt: bigint;
    updatedAt: bigint;
    items: Array<_PurchaseRequisitionItem>;
    department: string;
    requestedBy: string;
}): {
    id: PurchaseRequisitionId;
    totalEstimatedCost: number;
    status: PurchaseRequisitionStatus;
    justification: string;
    approvalHistory: Array<ApprovalRecord>;
    createdAt: bigint;
    updatedAt: bigint;
    items: Array<PurchaseRequisitionItem>;
    department: string;
    requestedBy: string;
} {
    return {
        id: value.id,
        totalEstimatedCost: value.totalEstimatedCost,
        status: from_candid_PurchaseRequisitionStatus_n3(_uploadFile, _downloadFile, value.status),
        justification: value.justification,
        approvalHistory: from_candid_vec_n5(_uploadFile, _downloadFile, value.approvalHistory),
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        items: value.items,
        department: value.department,
        requestedBy: value.requestedBy
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _QuotationId;
    status: _QuotationStatus;
    requestId: _QuotationRequestId;
    validityPeriod: _Time;
    termsAndConditions: string;
    vendorId: _VendorId;
    submissionDate: _Time;
    deliveryTimeline: string;
    unitPrice: number;
    totalPrice: number;
}): {
    id: QuotationId;
    status: QuotationStatus;
    requestId: QuotationRequestId;
    validityPeriod: Time;
    termsAndConditions: string;
    vendorId: VendorId;
    submissionDate: Time;
    deliveryTimeline: string;
    unitPrice: number;
    totalPrice: number;
} {
    return {
        id: value.id,
        status: from_candid_QuotationStatus_n30(_uploadFile, _downloadFile, value.status),
        requestId: value.requestId,
        validityPeriod: value.validityPeriod,
        termsAndConditions: value.termsAndConditions,
        vendorId: value.vendorId,
        submissionDate: value.submissionDate,
        deliveryTimeline: value.deliveryTimeline,
        unitPrice: value.unitPrice,
        totalPrice: value.totalPrice
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    action: _ApprovalAction;
    approverName: string;
    timestamp: bigint;
    comments: string;
}): {
    action: ApprovalAction;
    approverName: string;
    timestamp: bigint;
    comments: string;
} {
    return {
        action: from_candid_ApprovalAction_n8(_uploadFile, _downloadFile, value.action),
        approverName: value.approverName,
        timestamp: value.timestamp,
        comments: value.comments
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    closed: null;
} | {
    pending: null;
} | {
    received: null;
}): RequestStatus {
    return "closed" in value ? RequestStatus.closed : "pending" in value ? RequestStatus.pending : "received" in value ? RequestStatus.received : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    inactive: null;
}): VendorStatus {
    return "active" in value ? VendorStatus.active : "inactive" in value ? VendorStatus.inactive : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    submitted: null;
} | {
    rejected: null;
} | {
    shortlisted: null;
} | {
    accepted: null;
}): QuotationStatus {
    return "submitted" in value ? QuotationStatus.submitted : "rejected" in value ? QuotationStatus.rejected : "shortlisted" in value ? QuotationStatus.shortlisted : "accepted" in value ? QuotationStatus.accepted : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pendingApproval: null;
} | {
    approved: null;
} | {
    rejected: null;
} | {
    draft: null;
}): PurchaseRequisitionStatus {
    return "pendingApproval" in value ? PurchaseRequisitionStatus.pendingApproval : "approved" in value ? PurchaseRequisitionStatus.approved : "rejected" in value ? PurchaseRequisitionStatus.rejected : "draft" in value ? PurchaseRequisitionStatus.draft : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    submitted: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ApprovalAction {
    return "submitted" in value ? ApprovalAction.submitted : "approved" in value ? ApprovalAction.approved : "rejected" in value ? ApprovalAction.rejected : value;
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_QuotationRequest>): Array<QuotationRequest> {
    return value.map((x)=>from_candid_QuotationRequest_n10(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Vendor>): Array<Vendor> {
    return value.map((x)=>from_candid_Vendor_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PurchaseRequisition>): Array<PurchaseRequisition> {
    return value.map((x)=>from_candid_PurchaseRequisition_n1(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Quotation>): Array<Quotation> {
    return value.map((x)=>from_candid_Quotation_n28(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ApprovalRecord>): Array<ApprovalRecord> {
    return value.map((x)=>from_candid_ApprovalRecord_n6(_uploadFile, _downloadFile, x));
}
function to_candid_PurchaseRequisitionStatus_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PurchaseRequisitionStatus): _PurchaseRequisitionStatus {
    return to_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function to_candid_QuotationStatus_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuotationStatus): _QuotationStatus {
    return to_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function to_candid_RequestStatus_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RequestStatus): _RequestStatus {
    return to_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function to_candid_VendorStatus_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VendorStatus): _VendorStatus {
    return to_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PurchaseRequisitionStatus | null): [] | [_PurchaseRequisitionStatus] {
    return value === null ? candid_none() : candid_some(to_candid_PurchaseRequisitionStatus_n23(_uploadFile, _downloadFile, value));
}
function to_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PurchaseRequisitionStatus): {
    pendingApproval: null;
} | {
    approved: null;
} | {
    rejected: null;
} | {
    draft: null;
} {
    return value == PurchaseRequisitionStatus.pendingApproval ? {
        pendingApproval: null
    } : value == PurchaseRequisitionStatus.approved ? {
        approved: null
    } : value == PurchaseRequisitionStatus.rejected ? {
        rejected: null
    } : value == PurchaseRequisitionStatus.draft ? {
        draft: null
    } : value;
}
function to_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RequestStatus): {
    closed: null;
} | {
    pending: null;
} | {
    received: null;
} {
    return value == RequestStatus.closed ? {
        closed: null
    } : value == RequestStatus.pending ? {
        pending: null
    } : value == RequestStatus.received ? {
        received: null
    } : value;
}
function to_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuotationStatus): {
    submitted: null;
} | {
    rejected: null;
} | {
    shortlisted: null;
} | {
    accepted: null;
} {
    return value == QuotationStatus.submitted ? {
        submitted: null
    } : value == QuotationStatus.rejected ? {
        rejected: null
    } : value == QuotationStatus.shortlisted ? {
        shortlisted: null
    } : value == QuotationStatus.accepted ? {
        accepted: null
    } : value;
}
function to_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VendorStatus): {
    active: null;
} | {
    inactive: null;
} {
    return value == VendorStatus.active ? {
        active: null
    } : value == VendorStatus.inactive ? {
        inactive: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
